### ISSUE TITLE
One size is missing from .ico's

### ISSUE THREAD

**Issue by kaansoral** [idesis-gmbh/png2icons#5]
There are only 4 resolutions in the generated .ico files, after 256x256, I believe it drops to either 64x64 or 48x48 - My usecase is for Steam, as far as I inspect, regular steam .ico's all have 5 dimensions in them, http://www.png2ico.com/ seems to put 6 dimensions in a .ico file

I really like your tool, however, it would be really great to specify the dimensions for .ico's

**Comment by mn4367** [comment]
The current version creates the sizes 16, 32, 48 and 256. From what I've seen so far these size are quite common for Windows apps. I already have extended them with 512 and 768 since on newer Windows versions some apps seem to have really huge icons but that code isn't already on Github. However I can also add 64 and 128. That makes the generated file bigger (which is rather irrelevant today, I think) but it would keep the command line options as simple as they are now. Would that help?

**Comment by kaansoral** [comment]
Just saw your reply, yes that would help - I believe either 64 or 128 was needed

**Comment by mn4367** [comment]
Sorry for being much too late on this. Could you send me a link to a sample png which I can convert using the new sizes? I would convert it using the additional sizes and you can check if it works for you. Before pushing my changes I'd like to confirm that they are OK.

**Comment by mn4367** [comment]
Fixed with v2.0.0.
